function clayKind(title){if(/Cavity/.test(title))return "shield";if(/Caries|ปราศจาก/.test(title))return "tooth";if(/White|ตกกระ/.test(title))return "star";if(/20|ฟันแท้|คู่สบ|ฟันเทียม/.test(title))return "heart";return "clipboard"}
const TARGETS={"3":30,"12":20,"60-74":22};
const COLORS=["#a783ca","#eea899","#8cb9a2","#e2b85c"];
const state={view:"overview",age:"all",district:"",unit:"",query:""};
let DATA=[];
const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmt=n=>Number(n||0).toLocaleString("th-TH");
const pct=(num,den)=>den?100*num/den:null;
const val=(v,d=1,s="")=>v==null?"—":`${Number(v).toFixed(d)}${s}`;

function sum(rows){const out={};for(const row of rows)for(const [k,v] of Object.entries(row))if(typeof v==="number")out[k]=(out[k]||0)+v;return out}
function filtered(ignoreAge=false){return DATA.filter(r=>(ignoreAge||state.age==="all"||r.age===state.age)&&(!state.district||r.district===state.district)&&(!state.unit||r.unit===state.unit)&&(!state.query||[r.district,r.unit].some(v=>String(v||"").toLocaleLowerCase("th").includes(state.query))))}
function options(el,values,current){el.innerHTML='<option value="">ทั้งหมด</option>'+[...new Set(values)].sort((a,b)=>a.localeCompare(b,"th")).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join("");el.value=current&&[...el.options].some(o=>o.value===current)?current:"";return el.value}
function refreshFilterOptions(){const base=DATA.filter(r=>state.age==="all"||r.age===state.age);state.district=options($("#districtFilter"),base.map(r=>r.district),state.district);const d=base.filter(r=>!state.district||r.district===state.district);state.unit=options($("#unitFilter"),d.map(r=>r.unit),state.unit)}
function kpi(title,value,note,action=""){const kind=clayKind(title);const attrs=action?` role="button" tabindex="0" data-indicator="${action}" aria-label="เปิดรายละเอียด ${esc(title)}"`:"";return `<article class="card kpi tone-${kind}${action?" kpi-clickable":""}"${attrs}><img class="clay-icon" src="assets/clay/${kind}.svg" alt=""><div class="kpi-label">${title}</div><div class="kpi-value">${value}</div><div class="kpi-note">${note}${action?'<span class="click-hint">คลิกเพื่อดูรายละเอียดรายพื้นที่</span>':""}</div></article>`}
function aggregateBy(rows,key){const m=new Map();for(const r of rows){const k=r[key];if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return [...m].map(([name,items])=>({name,rows:items,total:sum(items)}))}

function verticalCaries(rows){const groups=aggregateBy(rows.filter(r=>r.age==="3"||r.age==="12"),"district").map(g=>{const a3=sum(g.rows.filter(r=>r.age==="3")),a12=sum(g.rows.filter(r=>r.age==="12"));return {name:g.name,v3:pct(a3.caries,a3.dental_den)||0,n3:a3.dental_den||0,f3:a3.caries||0,v12:pct(a12.caries,a12.dental_den)||0,n12:a12.dental_den||0,f12:a12.caries||0}}).sort((a,b)=>b.v3-a.v3);
  if(!groups.length)return '<div class="empty">ไม่มีข้อมูลตามตัวกรอง</div>';
  return `<div class="bar-chart"><div class="y-axis"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><div class="plot">${groups.map(g=>`<div class="bar-group"><button class="bar purple" style="height:${Math.max(0,g.v3)}%" data-age="3" data-district="${esc(g.name)}" title="${esc(g.name)} · เด็ก 3 ปี\nจำนวนทั้งหมด: ${g.n3} คน\nจำนวนที่พบ: ${g.f3} คน\nร้อยละ: ${g.v3.toFixed(1)}%"><span class="bar-label">${g.v3.toFixed(1)}%</span></button><button class="bar peach" style="height:${Math.max(0,g.v12)}%" data-age="12" data-district="${esc(g.name)}" title="${esc(g.name)} · เด็ก 12 ปี\nจำนวนทั้งหมด: ${g.n12} คน\nจำนวนที่พบ: ${g.f12} คน\nร้อยละ: ${g.v12.toFixed(1)}%"><span class="bar-label">${g.v12.toFixed(1)}%</span></button></div>`).join("")}</div><div></div><div class="x-labels">${groups.map(g=>`<div class="x-label"><span title="${esc(g.name)}">${esc(g.name)}</span></div>`).join("")}</div></div>`}
function donut(rows){const s=sum(rows.filter(r=>r.age==="60-74")),den=s.pair_den||0,items=[["0–3 คู่",s.pair_0||0],["≥4 คู่ ฟันแท้ล้วน",s.pair_1||0],["≥4 คู่ แท้+เทียม",s.pair_2||0],["≥4 คู่ เทียม+เทียม",s.pair_3||0]];if(!den)return '<div class="empty">ไม่มีข้อมูลตามตัวกรอง</div>';let start=0;const stops=items.map((x,i)=>{const end=start+100*x[1]/den,part=`${COLORS[i]} ${start}% ${end}%`;start=end;return part}).join(",");let angle=0;const labels=items.map(x=>{const value=100*x[1]/den,mid=(angle+value/2)*Math.PI/50;angle+=value;return x[1]?`<span class="slice-label" style="left:${50+38*Math.sin(mid)}%;top:${50-38*Math.cos(mid)}%">${value.toFixed(1)}%</span>`:""}).join("");return `<div class="donut-wrap"><div class="donut" style="background:conic-gradient(${stops})" title="จำนวนทั้งหมด ${den} คน">${labels}</div><div class="donut-legend">${items.map((x,i)=>`<div class="donut-row" title="จำนวนทั้งหมด: ${den} คน · จำนวนที่พบ: ${x[1]} คน · ร้อยละ: ${(100*x[1]/den).toFixed(1)}%"><i style="background:${COLORS[i]}"></i><span>${x[0]} <strong>${(100*x[1]/den).toFixed(1)}%</strong> (${fmt(x[1])})</span></div>`).join("")}</div></div>`}
function coverageRows(rows){const m=new Map();for(const r of rows){const k=[r.district,r.unit].join("|");if(!m.has(k))m.set(k,{district:r.district,unit:r.unit,"3":0,"12":0,"60-74":0});m.get(k)[r.age]+=r.n}return [...m.values()].sort((a,b)=>a.district.localeCompare(b.district,"th")||a.unit.localeCompare(b.unit,"th"))}
function statusIsComplete(status,current,target){const label=String(status||"").trim();if(label.startsWith("ยังไม่ครบ")||label.startsWith("ยังไม่มีข้อมูล"))return false;if(label.includes("ครบเป้าหมาย"))return true;const match=label.match(/\(([\d,]+)\s*\/\s*([\d,]+)\)/);if(match)return Number(match[1].replaceAll(",",""))>=Number(match[2].replaceAll(",",""));const currentNumber=Number(current),targetNumber=Number(target);return Number.isFinite(currentNumber)&&Number.isFinite(targetNumber)&&currentNumber>=targetNumber}
function badge(age,n){const target=Number(TARGETS[age]),current=Number(n),txt=current>=target?"ครบเป้าหมาย":current>0?"ยังไม่ครบ":"ยังไม่มีข้อมูล",cls=statusIsComplete(txt,current,target)?"status-complete":"status-incomplete";return `<span class="status-badge ${cls}">${txt} (${fmt(current)}/${target})</span>`}
function coverageTable(rows,age=null){const data=coverageRows(rows);if(age){const unitLabel=age==="3"?"ศพด./โรงเรียน/พื้นที่สุ่ม":age==="12"?"โรงเรียน/พื้นที่สุ่ม":"ชมรมผู้สูงอายุ/พื้นที่สุ่ม";return `<div class="table-wrap"><table class="age-detail-table"><thead><tr><th>อำเภอ</th><th>${unitLabel}</th><th>สถานะ/ผลสำรวจ ${age==="60-74"?"60–74":age} ปี</th></tr></thead><tbody>${data.map(r=>`<tr><td>${esc(r.district)}</td><td>${esc(r.unit)}</td><td>${badge(age,r[age])}</td></tr>`).join("")||'<tr><td colspan="3">ไม่มีข้อมูลตามตัวกรอง</td></tr>'}</tbody></table></div>`}return `<div class="table-wrap"><table><thead><tr><th>อำเภอ</th><th>โรงเรียน/พื้นที่สุ่ม</th><th>3 ปี</th><th>12 ปี</th><th>60–74 ปี</th></tr></thead><tbody>${data.map(r=>`<tr><td>${esc(r.district)}</td><td>${esc(r.unit)}</td><td>${badge("3",r["3"])}</td><td>${badge("12",r["12"])}</td><td>${badge("60-74",r["60-74"])}</td></tr>`).join("")||'<tr><td colspan="5">ไม่มีข้อมูลตามตัวกรอง</td></tr>'}</tbody></table></div>`}
function overview(){const rows=filtered(true),s=sum(rows),s3=sum(rows.filter(r=>r.age==="3")),s12=sum(rows.filter(r=>r.age==="12")),s60=sum(rows.filter(r=>r.age==="60-74"));return `<section class="kpis">${kpi("กลุ่มตัวอย่างสะสมทั้งหมด",fmt(s.n),`3 ปี ${fmt(s3.n)} / 12 ปี ${fmt(s12.n)} / 60–74 ปี ${fmt(s60.n)}`)}${kpi("เด็ก 3 ปีปราศจากฟันผุ",val(s3.dental_den?100-pct(s3.caries,s3.dental_den):null,1,"%"),`ตัวหาร n=${fmt(s3.dental_den)}`)}${kpi("DMFT เฉลี่ย เด็ก 12 ปี",val(s12.dental_den?s12.dental_sum/s12.dental_den:null),`ตัวหาร n=${fmt(s12.dental_den)}`)}${kpi("ผู้สูงอายุมีฟันแท้ ≥20 ซี่",val(pct(s60.teeth20,s60.teeth_den),1,"%"),`ตัวหาร n=${fmt(s60.teeth_den)}`)}</section><section class="section-grid"><article class="card"><h2>ความชุกโรคฟันผุ จำแนกรายอำเภอ</h2><div class="legend"><i class="dot purple"></i><span>เด็ก 3 ปี</span><i class="dot peach"></i><span>เด็ก 12 ปี</span><span class="hint">• คลิกที่แท่งกราฟเพื่อดูข้อมูลเฉพาะกลุ่มวัยและพื้นที่นั้น</span></div>${verticalCaries(rows)}</article><article class="card"><h2>คู่สบฟันหลังของผู้สูงอายุ</h2>${donut(rows)}</article></section><article class="card table-card"><div class="table-head"><h2>สรุปพื้นที่และความครอบคลุม</h2><button class="secondary" id="csvBtn">ส่งออก CSV</button></div>${coverageTable(rows)}</article>`}
function metricRows(items){return `<div class="metric-chart">${items.sort((a,b)=>(b[1]??-1)-(a[1]??-1)).map(([name,v])=>`<div class="metric-row"><span>${name}</span><div class="track"><div class="fill" style="width:${Math.max(0,Math.min(100,v||0))}%"></div></div><strong>${val(v,1,"%")}</strong></div>`).join("")}</div>`}
function countRows(items){const maximum=Math.max(1,...items.map(x=>x[1]||0));return `<div class="metric-chart">${items.sort((a,b)=>b[1]-a[1]).map(([name,v])=>`<div class="metric-row"><span>${name}</span><div class="track"><div class="fill" style="width:${100*v/maximum}%"></div></div><strong>${fmt(v)}</strong></div>`).join("")}</div>`}
function ageView(age){
  const rows=filtered(true).filter(r=>r.age===age),s=sum(rows),name=age==="3"?"เด็กปฐมวัย 3 ปี":age==="12"?"เด็ก 12 ปี":"ผู้สูงอายุ 60–74 ปี";
  const cariesFree=s.dental_den?100-pct(s.caries,s.dental_den):null;
  const cavityFree=pct(s.cavity_free,s.cavity_den);
  let cards,metrics;
  if(age==="3"){
    cards=[
      kpi("Caries Free (ปราศจากฟันผุ)",val(cariesFree,1,"%"),`dmft = 0 • ตัวหาร n=${fmt(s.dental_den)}`,"caries"),
      kpi("Cavity Free (ไม่มีรูผุ)",val(cavityFree,1,"%"),`d + m = 0 • ตัวหาร n=${fmt(s.cavity_den)}`,"cavity"),
      kpi("White Spot",val(pct(s.white_num,s.white_den),1,"%"),`มีรอยสีขาวขุ่น • ตัวหาร n=${fmt(s.white_den)}`,"white"),
      kpi("dmft เฉลี่ย",val(s.dental_den?s.dental_sum/s.dental_den:null,1," ซี่"),`ตัวหาร n=${fmt(s.dental_den)}`),
      kpi("จำนวนเด็กที่ตรวจ",fmt(s.n),`${coverageRows(rows).length} ศูนย์/หน่วยสำรวจ`)
    ];
    metrics=[["Caries Free",cariesFree],["Cavity Free",cavityFree],["White Spot",pct(s.white_num,s.white_den)]];
  }else if(age==="12"){
    cards=[
      kpi("Caries Free (ปราศจากฟันผุ)",val(cariesFree,1,"%"),`DMFT = 0 • ตัวหาร n=${fmt(s.dental_den)}`,"caries"),
      kpi("Cavity Free (ไม่มีรูผุ)",val(cavityFree,1,"%"),`D + M = 0 • ตัวหาร n=${fmt(s.cavity_den)}`,"cavity"),
      kpi("DMFT เฉลี่ย",val(s.dental_den?s.dental_sum/s.dental_den:null,1," ซี่"),`ตัวหาร n=${fmt(s.dental_den)}`),
      kpi("ฟันตกกระ",val(pct(s.fluor_num,s.fluor_den),1,"%"),`ตัวหาร n=${fmt(s.fluor_den)}`,"fluor"),
      kpi("เหงือกอักเสบ",val(pct(s.gum_num,s.gum_den),1,"%"),`ตัวหาร n=${fmt(s.gum_den)}`,"gum"),
      kpi("แปรงฟัน 2-2-2 ครบถ้วน",val(pct(s.brush_num,s.brush_den),1,"%"),`ตัวหาร n=${fmt(s.brush_den)}`)
    ];
    metrics=[["Caries Free",cariesFree],["Cavity Free",cavityFree],["ฟันตกกระ",pct(s.fluor_num,s.fluor_den)],["เหงือกอักเสบ",pct(s.gum_num,s.gum_den)],["ทำ 2-2-2 ครบ",pct(s.brush_num,s.brush_den)]];
  }else{
    cards=[kpi("ผู้สูงอายุที่ได้รับการตรวจ",fmt(s.n),`${coverageRows(rows).length} หน่วยสำรวจ`),kpi("ฟันแท้ใช้งานเฉลี่ย",val(s.teeth_den?s.teeth_sum/s.teeth_den:null,1," ซี่"),`n=${fmt(s.teeth_den)}`),kpi("มีฟันใช้งาน ≥20 ซี่",val(pct(s.teeth20,s.teeth_den),1,"%"),`n=${fmt(s.teeth_den)}`),kpi("มีคู่สบฟันหลัง ≥4 คู่",val(pct((s.pair_1||0)+(s.pair_2||0)+(s.pair_3||0),s.pair_den),1,"%"),`n=${fmt(s.pair_den)}`)];
    metrics=[["ฟันใช้งาน ≥20 ซี่",pct(s.teeth20,s.teeth_den)],["คู่สบฟันหลัง ≥4 คู่",pct((s.pair_1||0)+(s.pair_2||0)+(s.pair_3||0),s.pair_den)],["พบฟันเทียมหลวม",pct(s.loose_num,s.loose_den)]];
  }
  return `<section class="kpis">${cards.join("")}</section><section class="section-grid"><article class="card"><h2>ตัวชี้วัดสำคัญ · ${name}</h2>${metricRows(metrics)}</article><article class="card"><h2>จำนวนผู้สำรวจรายอำเภอ</h2>${countRows(aggregateBy(rows,"district").map(g=>[g.name,g.total.n]))}</article></section><article class="card table-card"><h2>รายละเอียดระดับหน่วยสำรวจ</h2>${coverageTable(rows,age)}</article>`
}
function indicatorConfig(age,key){const configs={caries:{title:"Caries Free (ปราศจากฟันผุ)",formula:age==="3"?"d + m + f = 0":"D + M + F = 0",den:"dental_den",found:r=>(r.dental_den||0)-(r.caries||0)},cavity:{title:"Cavity Free (ไม่มีรูผุ)",formula:age==="3"?"d + m = 0":"D + M = 0",den:"cavity_den",found:r=>r.cavity_free||0},white:{title:"White Spot (รอยสีขาวขุ่น)",formula:"พบ White Spot = 1",den:"white_den",found:r=>r.white_num||0},fluor:{title:"ฟันตกกระ",formula:"พบฟันตกกระ = 1",den:"fluor_den",found:r=>r.fluor_num||0},gum:{title:"เหงือกอักเสบ",formula:"พบเหงือกอักเสบ = 1",den:"gum_den",found:r=>r.gum_num||0}};return configs[key]}
function indicatorDetailRows(age,key){const cfg=indicatorConfig(age,key);return filtered(true).filter(r=>r.age===age&&r[cfg.den]).map(r=>{const total=r[cfg.den],found=cfg.found(r);return {district:r.district,tambon:r.tambon,unit:r.unit,year:r.year,total,found,rate:100*found/total}}).sort((a,b)=>b.rate-a.rate||a.district.localeCompare(b.district,"th"))}
function exportIndicatorDetail(rows,age,key){const cfg=indicatorConfig(age,key),head=["อำเภอ","ตำบล","หน่วยสำรวจ","ปี พ.ศ.","จำนวนทั้งหมด",`จำนวน ${cfg.title}`,"ร้อยละ"],csv=[head,...rows.map(r=>[r.district,r.tambon,r.unit,r.year,r.total,r.found,r.rate.toFixed(1)])].map(row=>row.map(x=>`"${String(x??"").replaceAll('"','""')}"`).join(",")).join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download=`${key}-${age}-years.csv`;a.click();URL.revokeObjectURL(a.href)}
function openIndicatorDetail(age,key){const cfg=indicatorConfig(age,key),all=indicatorDetailRows(age,key),ageTitle=age==="3"?"เด็กปฐมวัย 3 ปี":"เด็ก 12 ปี",modal=document.createElement("div");modal.className="modal-backdrop";modal.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-labelledby="indicatorTitle"><div class="modal-head"><div><h2 id="indicatorTitle">รายละเอียด ${cfg.title} · ${ageTitle}</h2><p>เกณฑ์ ${cfg.formula} • ข้อมูลสรุปแบบไม่ระบุตัวบุคคล</p></div><button class="modal-close" aria-label="ปิด">✕</button></div><div class="modal-tools"><input type="search" placeholder="ค้นหาอำเภอ ตำบล หรือหน่วยสำรวจ" aria-label="ค้นหารายละเอียด"><button class="secondary export-detail">ส่งออก CSV</button></div><div class="detail-summary"></div><div class="table-wrap detail-table"></div></section>`;document.body.appendChild(modal);const input=modal.querySelector("input"),table=modal.querySelector(".detail-table"),summary=modal.querySelector(".detail-summary");let shown=all;const draw=()=>{const q=input.value.trim().toLocaleLowerCase("th");shown=all.filter(r=>[r.district,r.tambon,r.unit,r.year].some(v=>String(v).toLocaleLowerCase("th").includes(q)));const total=shown.reduce((n,r)=>n+r.total,0),found=shown.reduce((n,r)=>n+r.found,0);summary.textContent=`พบ ${cfg.title} ${fmt(found)} คน จากข้อมูลที่ใช้คำนวณ ${fmt(total)} คน (${val(pct(found,total),1,"%")})`;table.innerHTML=`<table><thead><tr><th>อำเภอ</th><th>ตำบล</th><th>หน่วยสำรวจ</th><th>ปี พ.ศ.</th><th>ทั้งหมด</th><th>จำนวนที่พบ</th><th>ร้อยละ</th></tr></thead><tbody>${shown.map(r=>`<tr class="${r.found?"highlight":""}"><td>${esc(r.district)}</td><td>${esc(r.tambon)}</td><td>${esc(r.unit)}</td><td>${esc(r.year)}</td><td>${fmt(r.total)}</td><td>${fmt(r.found)}</td><td>${r.rate.toFixed(1)}%</td></tr>`).join("")||'<tr><td colspan="7">ไม่พบข้อมูล</td></tr>'}</tbody></table>`};draw();input.addEventListener("input",draw);modal.querySelector(".export-detail").onclick=()=>exportIndicatorDetail(shown,age,key);const close=()=>modal.remove();modal.querySelector(".modal-close").onclick=close;modal.addEventListener("click",e=>{if(e.target===modal)close()});modal.addEventListener("keydown",e=>{if(e.key==="Escape")close()});input.focus()}
function policy(){const rows=filtered(true).filter(r=>state.age==="all"||r.age===state.age),s=sum(rows),s3=sum(rows.filter(r=>r.age==="3")),s12=sum(rows.filter(r=>r.age==="12")),s60=sum(rows.filter(r=>r.age==="60-74"));const scope=state.age==="all"?"ทั้ง 3 กลุ่มวัย":state.age+" ปี";const what=state.age==="3"?[`ตรวจเด็ก 3 ปี ${fmt(s3.n)} คน`,`ปราศจากฟันผุ ${val(s3.dental_den?100-pct(s3.caries,s3.dental_den):null,1,"%")}`,`พบ White Spot ${val(pct(s3.white_num,s3.white_den),1,"%")}`]:state.age==="12"?[`ตรวจเด็ก 12 ปี ${fmt(s12.n)} คน`,`DMFT เฉลี่ย ${val(s12.dental_den?s12.dental_sum/s12.dental_den:null)}`,`ทำพฤติกรรม 2-2-2 ครบ ${val(pct(s12.brush_num,s12.brush_den),1,"%")}`]:state.age==="60-74"?[`ตรวจผู้สูงอายุ ${fmt(s60.n)} คน`,`ฟันแท้ใช้งานเฉลี่ย ${val(s60.teeth_den?s60.teeth_sum/s60.teeth_den:null,1," ซี่")}`,`มีฟันใช้งาน ≥20 ซี่ ${val(pct(s60.teeth20,s60.teeth_den),1,"%")}`]:[`ข้อมูลสะสม ${fmt(s.n)} คน`,`เด็ก 3 ปีปราศจากฟันผุ ${val(s3.dental_den?100-pct(s3.caries,s3.dental_den):null,1,"%")}`,`เด็ก 12 ปี DMFT เฉลี่ย ${val(s12.dental_den?s12.dental_sum/s12.dental_den:null)}`,`ผู้สูงอายุมีฟันใช้งาน ≥20 ซี่ ${val(pct(s60.teeth20,s60.teeth_den),1,"%")}`];return `<div class="hint">ขอบเขต: ${scope} • อำเภอ ${state.district||"ทั้งหมด"}</div><section class="policy-stack"><article class="card insight what"><h2>■ WHAT? สถานการณ์และข้อมูลสำคัญที่พบ</h2><ul>${what.map(x=>`<li>${x}</li>`).join("")}</ul></article><article class="card insight so"><h2>● SO WHAT? การตีความและผลกระทบ</h2><ul><li>ข้อมูลช่วยชี้พื้นที่และกลุ่มวัยที่ควรได้รับการติดตามก่อน โดยพิจารณาทั้งภาระโรคและความครบถ้วนของข้อมูล</li><li>ควรใช้พฤติกรรมและสภาพแวดล้อมร่วมกับผลตรวจ เพื่อกำหนดมาตรการที่ตรงกับบริบทของพื้นที่</li><li>ผลเป็นสถิติเชิงพรรณนาจากผู้ที่ได้รับการสำรวจ ไม่ได้ยืนยันเหตุและผล</li></ul></article><article class="card insight now"><h2>▶ NOW WHAT? ข้อเสนอแนะเชิงนโยบายและการขับเคลื่อน</h2><ul><li>จัดทำบัญชีพื้นที่เสี่ยงและติดตามตัวชี้วัดรายไตรมาสในระดับอำเภอ</li><li>เร่งมาตรการแปรงฟันคุณภาพ ลดหวาน และส่งต่อผู้ที่พบปัญหาเข้าสู่บริการ</li><li>ตรวจความครบถ้วนของข้อมูลก่อนใช้ประกอบการจัดสรรทรัพยากรหรือประเมินผล</li></ul></article></section>`}
function dataCenter(){return `<article class="card notice"><h2>ศูนย์จัดการข้อมูลและส่งออก</h2><p>เว็บไซต์นี้เผยแพร่เฉพาะข้อมูลสรุปแบบไม่ระบุตัวบุคคลจากฐานข้อมูลล่าสุด เพื่อการติดตามผลและนำเสนอผู้บริหาร</p><p>การนำเข้าไฟล์ Excel การตรวจข้อมูลซ้ำ และการแก้ไขข้อมูลต้นฉบับ ให้ดำเนินการผ่านโปรแกรม Oral Survey บนเครื่อง แล้วจึงเผยแพร่เว็บไซต์ฉบับใหม่</p><button class="primary" id="csvBtn">ส่งออกข้อมูลสรุป CSV</button></article>`}
function render(){const titles={overview:"ภาพรวมระดับพื้นที่",policy:"สรุปผลเชิงนโยบาย",coverage:"การมีข้อมูลแต่ละอำเภอ",age3:"เด็กปฐมวัย 3 ปี",age12:"เด็ก 12 ปี",age60:"ผู้สูงอายุ 60–74 ปี",data:"ศูนย์จัดการข้อมูลและส่งออก"},ageMap={overview:"all",age3:"3",age12:"12",age60:"60-74"};if(ageMap[state.view])state.age=ageMap[state.view];$("#pageTitle").textContent=titles[state.view];$("#ageFilter").value=state.age;$("#ageFilter").disabled=false;document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===state.view));const views={overview,policy,coverage:()=>`<article class="card"><h2>ความครบถ้วนของข้อมูลแต่ละพื้นที่</h2><div class="hint">เขียว = ครบเป้าหมาย • แดง = ยังไม่ครบหรือยังไม่มีข้อมูล</div>${coverageTable(filtered(true))}</article>`,age3:()=>ageView("3"),age12:()=>ageView("12"),age60:()=>ageView("60-74"),data:dataCenter};$("#content").innerHTML=views[state.view]();bindDynamic()}
function exportCsv(){const rows=coverageRows(filtered(true)),head=["อำเภอ","หน่วยสำรวจ","3 ปี","12 ปี","60-74 ปี"],csv=[head,...rows.map(r=>[r.district,r.unit,r["3"],r["12"],r["60-74"]])].map(row=>row.map(x=>`"${String(x).replaceAll('"','""')}"`).join(",")).join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download="oral-survey-summary.csv";a.click();URL.revokeObjectURL(a.href)}
function bindDynamic(){document.querySelectorAll(".bar[data-age]").forEach(b=>b.addEventListener("click",()=>{state.age=b.dataset.age;state.district=b.dataset.district;$("#ageFilter").value=state.age;refreshFilterOptions();state.view=state.age==="3"?"age3":"age12";render()}));document.querySelectorAll(".kpi[data-indicator]").forEach(card=>{const open=()=>openIndicatorDetail(state.view==="age3"?"3":"12",card.dataset.indicator);card.addEventListener("click",open);card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open()}})});$("#csvBtn")?.addEventListener("click",exportCsv)}
async function init(){const payload=await fetch("data.json").then(r=>{if(!r.ok)throw new Error("โหลดข้อมูลไม่สำเร็จ");return r.json()});DATA=payload.buckets;$("#updatedAt").textContent=`อัปเดต ${new Date(payload.generated_at).toLocaleString("th-TH")}`;for(let n=25;n<=125;n+=5)$("#zoom").add(new Option(`${n}%`,n));$("#zoom").value="60";$("#zoom").onchange=e=>{localStorage.setItem("oralZoom",e.target.value);document.documentElement.style.fontSize=`${16*e.target.value/100}px`};$("#zoom").onchange({target:$("#zoom")});$("#nav").addEventListener("click",e=>{const b=e.target.closest("button[data-view]");if(!b)return;state.view=b.dataset.view;const ageMap={overview:"all",age3:"3",age12:"12",age60:"60-74"};if(ageMap[state.view])state.age=ageMap[state.view];render()});$("#printBtn").onclick=()=>window.print();$("#ageFilter").onchange=e=>{state.age=e.target.value;state.view={all:"overview","3":"age3","12":"age12","60-74":"age60"}[state.age];refreshFilterOptions();render()};for(const [id,key] of [["districtFilter","district"],["unitFilter","unit"]])$("#"+id).onchange=e=>{state[key]=e.target.value;if(key==="district")state.unit="";refreshFilterOptions();render()};$("#searchFilter").oninput=e=>{state.query=e.target.value.trim().toLocaleLowerCase("th");render()};$("#resetFilters").onclick=()=>{state.view="overview";state.age="all";state.district="";state.unit="";state.query="";$("#ageFilter").value="all";$("#searchFilter").value="";refreshFilterOptions();render()};refreshFilterOptions();render()}
init().catch(error=>{$("#content").innerHTML=`<div class="card empty">${esc(error.message)}</div>`});
